export const SITE_URL = process.env.SITE_URL ?? 'https://wecodev.com'
export const SITE_LANG = 'en_US'
export const SITE_TITLE = 'wecodev'
export const SITE_MENTION = 'wecodev'
export const SITE_DESCRIPTION = 'We help you collaboratively develop.'
